### ISSUE TITLE
Image is repeated multiple times in v10

### ISSUE THREAD

**Issue by Oshcakes** [zeel01/TokenHUDArtButton#19]
Also does not fit window when shown.
![image](https://user-images.githubusercontent.com/61471647/187784550-c639923e-7f7d-476b-8ccf-b5a39b7703a8.png)

**Comment by vgeirnaert** [comment]
I tried to create a bugfix branch but repository permission settings do not allow it. This can easily be fixed by setting the style value of the .lightbox-image div in media-popout.html to

`background-image: url('{{image}}'); background-repeat: no-repeat; background-size: contain;`

**Comment by kiloforce** [comment]
> This can easily be fixed by setting the style value of the .lightbox-image div in media-popout.html to
> 
> `background-image: url('{{image}}'); background-repeat: no-repeat; background-size: contain;`
> 
> @zeel01 I have a created a PR for this: #21

Thanks, that worked for me!

**Comment by fatigues65** [comment]
This issue arises when using .webp  It does not occur when using a .png file as near as I can determine.

**Comment by rlach** [comment]
If someone doesn't want to edit their files "Custom CSS" module allows you to set this rule as well. Just paste this in "Global CSS" form of that module:
```
.lightbox-image {
  background-image: url('{{image}}'); background-repeat: no-repeat; background-size: contain;
}
```
I'm not sure @zeel01 is still accepting PRs for this module.

**Comment by zeel01** [comment]
I think the issue here is that Foundry changed the way the popups are formatted/styled. In fact, the custom popup class might not even still be needed? I haven't had the opportunity to fully evaluate yet. But this issue should be resolved now.
