### ISSUE TITLE
Token & actor name if the popup window

### ISSUE THREAD

**Issue by DarKDinDoN** [zeel01/TokenHUDArtButton#2]
Hello,

One issue with the current state of the module is that whenever the GM shows a token artwork to the players, the window also shows the name of the actor. Even tho, the name should remain secret.

Can you not display the name in the window, unless:
- nameplate is configured to be shown on "hover" or "always" in the token configuration
- permissions on the actor is set to something else that "None"

Thx

**Comment by zeel01** [comment]
I'll look into it.

**Comment by zeel01** [comment]
Added v0.2.1
