### ISSUE TITLE
Image popout title is wrong

### ISSUE THREAD

**Issue by DarKDinDoN** [zeel01/TokenHUDArtButton#3]
Hello,

Thanks for the last update! But I think the names are wrong.

Whether the nameplate is considered hidden or visible ("hover" or "always"), the popout title is always the same: "Character Name".

Also, this line is looking for a DnD5 translation. Meaning it won't work for other system. And your module is "system agnostic".
```javascript
let hiddenName = game.i18n.localize("DND5E.Name");
```

I suggest you use your own module translation for this string.

**Comment by zeel01** [comment]
Huh, not sure why I never saw this issue.

Very good point, will be corrected in the next version.
```json
	"TKNHAB.TileImg": "Tile Image",
	"TKNHAB.ActorImg": "Actor Image",
	"TKNHAB.TokenImg": "Token Image"
```
