### ISSUE TITLE
More show artwork

### ISSUE THREAD

**Issue by DeadlyArtist** [zeel01/TokenHUDArtButton#5]
I have a request for three optional (changeable in settings) features:

1. Show artwork to myself as well when pressing Show Artwork. Best would be shift, ctrl and alt to show art others & myself, only myself and only others respectively. Make shift and alt swappable in settings.
2. A button when right clicking on a token to show myself artwork. Make option in settings whether only the owner can see that or all. (I believe maptools does this)
3. Show the artwork of a token upon selecting it (left or right click) in the bottom left corner. Make option to enable and disable that behaviour and whether it only works for owned tokens.

Button somewhere there. 
![image](https://user-images.githubusercontent.com/44524817/96286511-c6f57c80-0fe0-11eb-9f9e-b639aca31bca.png)

Show artwork when selecting token here.
![image](https://user-images.githubusercontent.com/44524817/96287059-a5e15b80-0fe1-11eb-81c7-d7331ee149d9.png)

**Comment by zeel01** [comment]
I'm somewhat confused by this request, as it mainly seems like what the module already does. You may be confusing this module with this one: [Show Artwork](https://foundryvtt.com/packages/ShowArtwork/)? This module adds a button to the token HUD (request 2) and will show the art to the current user (request 1).

The third request is likely out of scope for either module, as it would require a significantly different method of handling than currently available, it would likely make much more sense as a stand-alone module.

**Comment by DeadlyArtist** [comment]
Bro I'm confused af right now. I think I meant the other module. But anyways installed this module now and happy with it.

But my 3rd request still stands :)

**Comment by zeel01** [comment]
I think this feature is probably out of scope.
